# version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ollama-app
    container_name: ollama-app
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - ollama
      - ollama-webui
    deploy:
      resources:
        limits:
          cpus: '.25'
          memory: 200M
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:0.21.1
    ports:
      - 9090:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_DEBUG=0
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      # reduce context size
      - OLLAMA_CONTEXT_LENGTH=2048
      # reduces the memory required to process long strings of text.
      - OLLAMA_FLASH_ATTENTION=1
    # Limit resources given to the container
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 30G
    networks:
      - ollama-docker

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:git-b03fc97
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '.5'
          memory: 300M
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
  
