version: '3.8'

services:
  app:
    build: ./src/portal
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./src/portal:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    depends_on:
      - ollama
      - ollama-webui
    networks:
      - ollama-docker
      
  ollama:
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:0.5.13
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:git-b03fc97
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      # - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - OLLAMA_BASE_URLS=http://ollama:11434 #this connection from within the docker networks better than the previous setting!! 
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - ollama-docker

  firefox:
    image: jlesage/firefox
    hostname: firefox
    container_name: firefox
    ports:
      - 5800:5800
    networks:
      - ollama-docker
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.1'
    #       memory: 1G
    #     reservations:
    #       cpus: '0.05'
    #       memory: 500M


networks:
  ollama-docker:
    external: false
